# Indicator Tutorial

The purpose of this spreadsheet is to demonstrate the custom indicators that pinkfish provides.

In [1]:
%%javascript
IPython.OutputArea.prototype._should_scroll = function(lines) {
    return false;
}

In [2]:
import datetime
import pandas as pd
import pinkfish as pf

# Format price data
pd.options.display.float_format = '{:0.3f}'.format

Some global data

In [3]:
symbol = 'SPY'
start = datetime.datetime(2000, 1, 1)
end = datetime.datetime(2020, 1, 1)

Fetch symbol data from cache, if available.

In [4]:
ts = pf.fetch_timeseries(symbol)
ts.tail()

              open    high     low   close  adj_close    volume
date
2021-11-09 469.320 469.570 465.880 467.380    467.380  51149100
2021-11-10 465.580 467.380 462.040 463.620    463.620  69429700
2021-11-11 465.210 465.290 463.750 463.770    463.770  34848500
2021-11-12 465.120 467.860 464.110 467.270    467.270  53423300
2021-11-15 468.640 468.788 466.230 467.430    467.430  40042473

Select timeseries between start and end.

In [5]:
ts = pf.select_tradeperiod(ts, start, end)
ts.head()

              open    high     low   close  adj_close   volume
date
1999-01-04 123.375 125.219 121.719 123.031     81.346  9450400
1999-01-05 122.938 124.875 122.938 124.438     82.276  8031000
1999-01-06 125.812 127.750 125.750 127.438     84.259  7737700
1999-01-07 126.375 127.219 125.781 126.812     83.846  5504900
1999-01-08 128.188 128.500 125.969 127.750     84.466  6224400

### SMA Indicator

In [6]:
print(pf.SMA.__doc__)

    This indicator computes a simple moving average.

    Can be used in place of talib SMA.

    ts : pd.DateFrame or pd.Series
        A dataframe with 'open', 'high', 'low', 'close', 'volume' or
        a series of price data.
    timeperiod: int, optional
        The timeperiod for the moving average (default is 30).
    price : str, optional {'close', 'open', 'high', 'low'}
        Input_array column to use for price (default is 'close').
        Not used if `ts` is a series.

    Returns
    -------
    pd.Series
        Series that contains the simple moving average.

    Examples
    --------
    >>> ts['sma50'] = pf.SMA(ts, timeperiod=50)

In [7]:
ts['sma50'] = pf.SMA(ts, timeperiod=50)
ts.tail(10)

              open    high     low   close  adj_close     volume   sma50
date
2019-12-17 319.920 320.250 319.480 319.570    309.152   61097700 307.105
2019-12-18 320.000 320.250 319.530 319.590    309.172   48133000 307.726
2019-12-19 319.800 320.980 319.520 320.900    310.439   85310500 308.319
2019-12-20 320.460 321.970 319.390 320.730    311.800  147142100 308.869
2019-12-23 321.590 321.650 321.060 321.220    312.276   52990000 309.368
2019-12-24 321.470 321.520 320.900 321.230    312.286   20270000 309.873
2019-12-26 321.650 322.950 321.640 322.940    313.949   30911200 310.354
2019-12-27 323.740 323.800 322.280 322.860    313.871   42528800 310.844
2019-12-30 322.950 323.100 320.550 321.080    312.140   49729100 311.280
2019-12-31 320.530 322.130 320.150 321.860    312.899   57077300 311.757

### EMA Indicator

In [8]:
print(pf.EMA.__doc__)

    This indicator computes an exponential moving average.

    Can be used in place of talib EMA.

    ts : pd.DateFrame or pd.Series
        A dataframe with 'open', 'high', 'low', 'close', 'volume' or
        a series of price data.
    timeperiod: int, optional
        The timeperiod for the moving average (default is 30).
    price : str, optional {'close', 'open', 'high', 'low'}
        Input_array column to use for price (default is 'close').
        Not used if `ts` is a series.

    Returns
    -------
    pd.Series
        Series that contains the simple moving average.

    Examples
    --------
    >>> ts['ema50'] = pf.EMA(ts, timeperiod=50)

In [9]:
ts['ema50'] = pf.EMA(ts, timeperiod=50)
ts.tail(10)

,open,high,low,close,adj_close,volume,sma50,ema50
date,,,,,,,,
2019-12-17,319.920,320.250,319.480,319.570,309.152,61097700,307.105,308.584
2019-12-18,320.000,320.250,319.530,319.590,309.172,48133000,307.726,309.015
2019-12-19,319.800,320.980,319.520,320.900,310.439,85310500,308.319,309.481
2019-12-20,320.460,321.970,319.390,320.730,311.800,147142100,308.869,309.922
2019-12-23,321.590,321.650,321.060,321.220,312.276,52990000,309.368,310.366
2019-12-24,321.470,321.520,320.900,321.230,312.286,20270000,309.873,310.792
2019-12-26,321.650,322.950,321.640,322.940,313.949,30911200,310.354,311.268
2019-12-27,323.740,323.800,322.280,322.860,313.871,42528800,310.844,311.723
2019-12-30,322.950,323.100,320.550,321.080,312.140,49729100,311.280,312.090
2019-12-31,320.530,322.130,320.150,321.860,312.899,57077300,311.757,312.473

### CROSSOVER Indicator

In [10]:
print(pf.CROSSOVER.__doc__)

    This indicator is used to represent regime direction and duration.

    For example, an indicator value of 50 means a bull market that has
    persisted for 50 days, whereas -20 means a bear market that has
    persisted for 20 days.

    More generally, this is a crossover indicator for two moving
    averages.  The indicator is positive when the fast moving average
    is above the slow moving arverage, and negative when the fast
    moving average is below the slow moving average.

    Parameters
    ----------
    ts : pd.DateFrame
        A dataframe with 'open', 'high', 'low', 'close', 'volume'.
    timeperiod_fast : int, optional
        The timeperiod for the fast moving average (default is 50).
    timeperiod_slow : int, optional
        The timeperiod for the slow moving average (default is 200).
    func_fast : Function, optional
        {pf.SMA, pf.EMA} (pinkfish functions) or
        {SMA, DEMA, EMA, KAMA, T3, TEMA, TRIMA, WMA} (ta-lib functions)
        The function for fast moving average (default is pf.SMA).
        MAMA not compatible.
    func_slow : Function, optional
         {pf.SMA, pf.EMA} (pinkfish functions) or
        {SMA, DEMA, EMA, KAMA, T3, TEMA, TRIMA, WMA} (ta-lib functions)
        The function for fast moving average (default is pf.SMA).
        MAMA not compatible.
    band : float, {0-100}, optional
        Percent band around the slow moving average.
        (default is 0, which implies no band is used).
    price : str, optional {'close', 'open', 'high', 'low'}
        Input_array column to use for price (default is 'close').
    prevday : bool, optional
        True will shift the series forward.  Unless you are buying
        on the close, you'll likely want to set this to True.
        It gives you the previous day's CrossOver (default is False).

    Returns
    -------
    s : pd.Series
        Series that contains the rolling regime indicator values.

    Raises
    ------
    TradeCrossOverError
        If one of the timeperiods specified is invalid.

    Examples
    --------
    >>> ts['regime'] = pf.CROSSOVER(ts, timeperiod_fast=50,
                                    timeperiod_slow=200)

In [11]:
# We see that SPY has been in a bull market regime for nearly 200 days.
ts['regime'] = pf.CROSSOVER(ts, timeperiod_fast=50, timeperiod_slow=200)
ts.tail(10)

,open,high,low,close,adj_close,volume,sma50,ema50,regime
date,,,,,,,,,
2019-12-17,319.920,320.250,319.480,319.570,309.152,61097700,307.105,308.584,182.000
2019-12-18,320.000,320.250,319.530,319.590,309.172,48133000,307.726,309.015,183.000
2019-12-19,319.800,320.980,319.520,320.900,310.439,85310500,308.319,309.481,184.000
2019-12-20,320.460,321.970,319.390,320.730,311.800,147142100,308.869,309.922,185.000
2019-12-23,321.590,321.650,321.060,321.220,312.276,52990000,309.368,310.366,186.000
2019-12-24,321.470,321.520,320.900,321.230,312.286,20270000,309.873,310.792,187.000
2019-12-26,321.650,322.950,321.640,322.940,313.949,30911200,310.354,311.268,188.000
2019-12-27,323.740,323.800,322.280,322.860,313.871,42528800,310.844,311.723,189.000
2019-12-30,322.950,323.100,320.550,321.080,312.140,49729100,311.280,312.090,190.000
2019-12-31,320.530,322.130,320.150,321.860,312.899,57077300,311.757,312.473,191.000

### MOMENTUM Indicator

In [12]:
print(pf.MOMENTUM.__doc__)

    This indicator is used to represent momentum is security prices.

    Percent price change is used to calculate momentum.  Momentum
    is positive if the price since the lookback period has increased.
    Likewise, if price has decreased since the lookback period,
    momentum is negative.  Percent change is used to normalize
    asset prices for comparison.

    Parameters
    ----------
    ts : pd.DateFrame
        A dataframe with 'open', 'high', 'low', 'close', 'volume'.
    lookback : int, optional
        The number of time frames to lookback, e.g. 2 months
        (default is 1).
    timeframe : str, optional {'monthly', 'daily', 'weekly', 'yearly'}
        The unit or timeframe type of lookback (default is 'monthly').
    price : str, optional {'close', 'open', 'high', 'low'}
        Input_array column to use for price (default is 'close').
    prevday : bool, optional
        True will shift the series forward.  Unless you are buying
        on the close, you'll likely want to set this to True.
        It gives you the previous day's Momentum (default is False).

    Returns
    -------
    s : pd.Series
        Series that contains the rolling momentum indicator values.

    Raises
    ------
    ValueError
        If the lookback is not positive or the time_frame is invalid.

    Examples
    --------
    >>> ts['mom'] = pf.MOMENTUM(ts, lookback=6, time_frame='monthly')

In [13]:
# We see that SPY has positive momentum.  Over the last 6 months
# the price has increased by about 8%.
ts['mom'] = pf.MOMENTUM(ts, lookback=6, time_frame='monthly')
ts.tail(10)

,open,high,low,close,adj_close,volume,sma50,ema50,regime,mom
date,,,,,,,,,,
2019-12-17,319.920,320.250,319.480,319.570,309.152,61097700,307.105,308.584,182.000,0.096
2019-12-18,320.000,320.250,319.530,319.590,309.172,48133000,307.726,309.015,183.000,0.091
2019-12-19,319.800,320.980,319.520,320.900,310.439,85310500,308.319,309.481,184.000,0.085
2019-12-20,320.460,321.970,319.390,320.730,311.800,147142100,308.869,309.922,185.000,0.082
2019-12-23,321.590,321.650,321.060,321.220,312.276,52990000,309.368,310.366,186.000,0.075
2019-12-24,321.470,321.520,320.900,321.230,312.286,20270000,309.873,310.792,187.000,0.076
2019-12-26,321.650,322.950,321.640,322.940,313.949,30911200,310.354,311.268,188.000,0.088
2019-12-27,323.740,323.800,322.280,322.860,313.871,42528800,310.844,311.723,189.000,0.086
2019-12-30,322.950,323.100,320.550,321.080,312.140,49729100,311.280,312.090,190.000,0.075
2019-12-31,320.530,322.130,320.150,321.860,312.899,57077300,311.757,312.473,191.000,0.075

### VOLATILITY Indicator

In [14]:
print(pf.VOLATILITY.__doc__)

    This indicator is used to represent volatility in security prices.

    Volatility is represented as the standard deviation.  Volatility
    is calculated over the lookback period, then we scale to the
    time frame.  Volatility scales with the square root of time.
    For example,  if the market’s daily volatility is 0.5%, then
    volatility for two days is the square root of 2 times
    the daily volatility (0.5% * 1.414 = 0.707%).  We use the square
    root of time to scale from daily to weely, monthly, or yearly.

    Parameters
    ----------
    ts : pd.DateFrame
        A dataframe with 'open', 'high', 'low', 'close', 'volume'.
    lookback : int, optional
        The number of time frames to lookback, e.g. 2 months
        (default is 1).
    timeframe : str, optional {'yearly', 'daily', 'weekly', 'monthly'}
        The unit or timeframe used for scaling.  For example, if the
        lookback is 20 and the timeframe is 'yearly', then we compute
        the 20 day volatility and scale to 1 year.
        (default is 'yearly').
    downside : bool, optional
        True to calculate the downside volatility (default is False).
    price : str, optional {'close', 'open', 'high', 'low'}
        Input_array column to use for price (default is 'close').
    prevday : bool, optional
        True will shift the series forward.  Unless you are buying
        on the close, you'll likely want to set this to True.
        It gives you the previous day's Volatility (default is False).

    Returns
    -------
    s : pd.Series
        A new column that contains the rolling volatility.

    Raises
    ------
    ValueError
        If the lookback is not positive or the time_frame is invalid.

    Examples
    --------
    >>> ts['vola'] = pf.VOLATILITY(ts, lookback=20, time_frame='yearly')

In [15]:
# We compute the annualized 20 days volatility.  Notice that the
# volatility is decreasing.
ts['vola'] = pf.VOLATILITY(ts, lookback=20, time_frame='yearly')
ts.tail(10)

,open,high,low,close,adj_close,volume,sma50,ema50,regime,mom,vola
date,,,,,,,,,,,
2019-12-17,319.920,320.250,319.480,319.570,309.152,61097700,307.105,308.584,182.000,0.096,0.079
2019-12-18,320.000,320.250,319.530,319.590,309.172,48133000,307.726,309.015,183.000,0.091,0.079
2019-12-19,319.800,320.980,319.520,320.900,310.439,85310500,308.319,309.481,184.000,0.085,0.078
2019-12-20,320.460,321.970,319.390,320.730,311.800,147142100,308.869,309.922,185.000,0.082,0.077
2019-12-23,321.590,321.650,321.060,321.220,312.276,52990000,309.368,310.366,186.000,0.075,0.077
2019-12-24,321.470,321.520,320.900,321.230,312.286,20270000,309.873,310.792,187.000,0.076,0.074
2019-12-26,321.650,322.950,321.640,322.940,313.949,30911200,310.354,311.268,188.000,0.088,0.075
2019-12-27,323.740,323.800,322.280,322.860,313.871,42528800,310.844,311.723,189.000,0.086,0.074
2019-12-30,322.950,323.100,320.550,321.080,312.140,49729100,311.280,312.090,190.000,0.075,0.076
2019-12-31,320.530,322.130,320.150,321.860,312.899,57077300,311.757,312.473,191.000,0.075,0.067

### ANNUALIZED_RETURNS Indicator

In [16]:
print(pf.ANNUALIZED_RETURNS.__doc__)

    Calculate the rolling annualized returns.

    Parameters
    ----------
    ts : pd.DateFrame
        A dataframe with 'open', 'high', 'low', 'close', 'volume'.
    lookback : float, optional
        The number of years to lookback, e.g. 5 years.  1/12 can be
        used for 1 month.  Likewise 3/12 for 3 months, etc...
        (default is 5).
    price : str, optional {'close', 'open', 'high', 'low'}
        Input_array column to use for price (default is 'close').
    prevday : bool, optional
        True will shift the series forward.  Unless you are buying
        on the close, you'll likely want to set this to True.
        It gives you the previous day's Volatility (default is False).

    Returns
    -------
    s : pd.Series
        Series that contains the rolling annualized returns.

    Raises
    ------
    ValueError
        If the lookback is not positive.

    Examples
    --------
    >>> annual_returns_1mo = pf.ANNUALIZED_RETURNS(ts, lookback=1/12)
    >>> annual_returns_3mo = pf.ANNUALIZED_RETURNS(ts, lookback=3/12)
    >>> annual_returns_1yr = pf.ANNUALIZED_RETURNS(ts, lookback=1)
    >>> annual_returns_3yr = pf.ANNUALIZED_RETURNS(ts, lookback=3)
    >>> annual_returns_5yr = pf.ANNUALIZED_RETURNS(ts, lookback=5)

In [17]:
# The 3 month annualized returns are about 18%.
ts['rets'] = pf.ANNUALIZED_RETURNS(ts, lookback=3/12)
ts.tail(10)

,open,high,low,close,adj_close,volume,sma50,ema50,regime,mom,vola,rets
date,,,,,,,,,,,,
2019-12-17,319.920,320.250,319.480,319.570,309.152,61097700,307.105,308.584,182.000,0.096,0.079,0.095
2019-12-18,320.000,320.250,319.530,319.590,309.172,48133000,307.726,309.015,183.000,0.091,0.079,0.110
2019-12-19,319.800,320.980,319.520,320.900,310.439,85310500,308.319,309.481,184.000,0.085,0.078,0.116
2019-12-20,320.460,321.970,319.390,320.730,311.800,147142100,308.869,309.922,185.000,0.082,0.077,0.128
2019-12-23,321.590,321.650,321.060,321.220,312.276,52990000,309.368,310.366,186.000,0.075,0.077,0.121
2019-12-24,321.470,321.520,320.900,321.230,312.286,20270000,309.873,310.792,187.000,0.076,0.074,0.125
2019-12-26,321.650,322.950,321.640,322.940,313.949,30911200,310.354,311.268,188.000,0.088,0.075,0.142
2019-12-27,323.740,323.800,322.280,322.860,313.871,42528800,310.844,311.723,189.000,0.086,0.074,0.134
2019-12-30,322.950,323.100,320.550,321.080,312.140,49729100,311.280,312.090,190.000,0.075,0.076,0.144
2019-12-31,320.530,322.130,320.150,321.860,312.899,57077300,311.757,312.473,191.000,0.075,0.067,0.176

## ANNUALIZED_STANDARD_DEVIATION Indicator

In [18]:
print(pf.ANNUALIZED_STANDARD_DEVIATION.__doc__)

    Calculate the rolling annualized standard deviation.

    Parameters
    ----------
    ts : pd.DateFrame
        A dataframe with 'open', 'high', 'low', 'close', 'volume'.
    lookback : float, optional
        The number of years to lookback, e.g. 5 years.  1/12 can be
        used for 1 month.  Likewise 3/12 for 3 months, etc...
        (default is 5).
    price : str, optional {'close', 'open', 'high', 'low'}
        Input_array column to use for price (default is 'close').
    prevday : bool, optional
        True will shift the series forward.  Unless you are buying
        on the close, you'll likely want to set this to True.
        It gives you the previous day's Volatility (default is False).

    Returns
    -------
    s : pd.Series
        Series that contains the rolling annualized standard deviation.

    Raises
    ------
    ValueError
        If the lookback is not positive.

    Examples
    --------
    >>> std_dev_1mo = pf.ANNUALIZED_STANDARD_DEVIATION(ts,lookback=1/12)
    >>> std_dev_3mo = pf.ANNUALIZED_STANDARD_DEVIATION(ts, lookback=3/12)
    >>> std_dev_1yr = pf.ANNUALIZED_STANDARD_DEVIATION(ts, lookback=1)
    >>> std_dev_3yr = pf.ANNUALIZED_STANDARD_DEVIATION(ts, lookback=3)
    >>> std_dev_5yr = pf.ANNUALIZED_STANDARD_DEVIATION(ts, lookback=5)

In [19]:
# The 3 year annualized standard deviation is about 13%.
ts['std_dev'] = pf.ANNUALIZED_STANDARD_DEVIATION(ts, lookback=3)
ts.tail(10)

,open,high,low,close,adj_close,volume,sma50,ema50,regime,mom,vola,rets,std_dev
date,,,,,,,,,,,,,
2019-12-17,319.920,320.250,319.480,319.570,309.152,61097700,307.105,308.584,182.000,0.096,0.079,0.095,0.129
2019-12-18,320.000,320.250,319.530,319.590,309.172,48133000,307.726,309.015,183.000,0.091,0.079,0.110,0.129
2019-12-19,319.800,320.980,319.520,320.900,310.439,85310500,308.319,309.481,184.000,0.085,0.078,0.116,0.129
2019-12-20,320.460,321.970,319.390,320.730,311.800,147142100,308.869,309.922,185.000,0.082,0.077,0.128,0.129
2019-12-23,321.590,321.650,321.060,321.220,312.276,52990000,309.368,310.366,186.000,0.075,0.077,0.121,0.129
2019-12-24,321.470,321.520,320.900,321.230,312.286,20270000,309.873,310.792,187.000,0.076,0.074,0.125,0.129
2019-12-26,321.650,322.950,321.640,322.940,313.949,30911200,310.354,311.268,188.000,0.088,0.075,0.142,0.129
2019-12-27,323.740,323.800,322.280,322.860,313.871,42528800,310.844,311.723,189.000,0.086,0.074,0.134,0.129
2019-12-30,322.950,323.100,320.550,321.080,312.140,49729100,311.280,312.090,190.000,0.075,0.076,0.144,0.129
2019-12-31,320.530,322.130,320.150,321.860,312.899,57077300,311.757,312.473,191.000,0.075,0.067,0.176,0.129

## ANNUALIZED_SHARPE_RATIO Indicator

In [20]:
print(pf.ANNUALIZED_SHARPE_RATIO.__doc__)

    Calculate the rolling annualized sharpe ratio.

    Parameters
    ----------
    ts : pd.DateFrame
        A dataframe with 'open', 'high', 'low', 'close', 'volume'.
    lookback : float, optional
        The number of years to lookback, e.g. 5 years.  1/12 can be
        used for 1 month.  Likewise 3/12 for 3 months, etc...
        (default is 5).
    price : str, optional {'close', 'open', 'high', 'low'}
        Input_array column to use for price (default is 'close').
    prevday : bool, optional
        True will shift the series forward.  Unless you are buying
        on the close, you'll likely want to set this to True.
        It gives you the previous day's Volatility (default is False).
    risk_free: float, optional
        The risk free rate (default is 0).

    Returns
    -------
    s : pd.Series
        Series that contains the rolling annualized sharpe ratio.

    Raises
    ------
    ValueError
        If the lookback is not positive.

    Examples
    --------
    >>> sharpe_ratio_1mo = pf.ANNUALIZED_SHARPE_RATIO(ts, lookback=1/12)
    >>> sharpe_ratio_3mo = pf.ANNUALIZED_SHARPE_RATIO(ts, lookback=3/12)
    >>> sharpe_ratio_1yr = pf.ANNUALIZED_SHARPE_RATIO(ts, lookback=1)
    >>> sharpe_ratio_3yr = pf.ANNUALIZED_SHARPE_RATIO(ts, lookback=3)
    >>> sharpe_ratio_5yr = pf.ANNUALIZED_SHARPE_RATIO(ts, lookback=5)

In [21]:
# The 3 year annualized sharpe ratio is about 1.7.
ts['sharpe_ratio'] = pf.ANNUALIZED_SHARPE_RATIO(ts, lookback=3)
ts.tail(10)

,open,high,low,close,adj_close,volume,sma50,ema50,regime,mom,vola,rets,std_dev,sharpe_ratio
date,,,,,,,,,,,,,,
2019-12-17,319.920,320.250,319.480,319.570,309.152,61097700,307.105,308.584,182.000,0.096,0.079,0.095,0.129,1.669
2019-12-18,320.000,320.250,319.530,319.590,309.172,48133000,307.726,309.015,183.000,0.091,0.079,0.110,0.129,1.651
2019-12-19,319.800,320.980,319.520,320.900,310.439,85310500,308.319,309.481,184.000,0.085,0.078,0.116,0.129,1.705
2019-12-20,320.460,321.970,319.390,320.730,311.800,147142100,308.869,309.922,185.000,0.082,0.077,0.128,0.129,1.693
2019-12-23,321.590,321.650,321.060,321.220,312.276,52990000,309.368,310.366,186.000,0.075,0.077,0.121,0.129,1.683
2019-12-24,321.470,321.520,320.900,321.230,312.286,20270000,309.873,310.792,187.000,0.076,0.074,0.125,0.129,1.695
2019-12-26,321.650,322.950,321.640,322.940,313.949,30911200,310.354,311.268,188.000,0.088,0.075,0.142,0.129,1.727
2019-12-27,323.740,323.800,322.280,322.860,313.871,42528800,310.844,311.723,189.000,0.086,0.074,0.134,0.129,1.719
2019-12-30,322.950,323.100,320.550,321.080,312.140,49729100,311.280,312.090,190.000,0.075,0.076,0.144,0.129,1.683
2019-12-31,320.530,322.130,320.150,321.860,312.899,57077300,311.757,312.473,191.000,0.075,0.067,0.176,0.129,1.732

## COMBINATION of INDICATORS

Here's how to combine 2 indicators to create a new one.  
SMA_MOMENTUM = SMA(MOMENTUM)  


We first calculate the MOM, then apply a SMA to it.

In [22]:
from talib.abstract import *

def SMA_MOMENTUM(ts, mom_lookback=1, sma_timeperiod=20, price='close'):
    """ Returns a series which is an SMA with of a daily MOM. """
    mom = pf.MOMENTUM(ts, lookback=mom_lookback, time_frame='daily', price=price)
    sma_mom = SMA(mom, timeperiod=sma_timeperiod)
    return sma_mom

In [23]:
# We see that SPY has positive sma momentum.  Over the last 20 days
# the average 5 day momenteum (averaged over 20 samples) has been positive
# at about 0.7%.
ts['sma_mom'] = SMA_MOMENTUM(ts, mom_lookback=5, sma_timeperiod=20)
ts.tail(10)

,open,high,low,close,adj_close,volume,sma50,ema50,regime,mom,vola,rets,std_dev,sharpe_ratio,sma_mom
date,,,,,,,,,,,,,,,
2019-12-17,319.920,320.250,319.480,319.570,309.152,61097700,307.105,308.584,182.000,0.096,0.079,0.095,0.129,1.669,0.006
2019-12-18,320.000,320.250,319.530,319.590,309.172,48133000,307.726,309.015,183.000,0.091,0.079,0.110,0.129,1.651,0.006
2019-12-19,319.800,320.980,319.520,320.900,310.439,85310500,308.319,309.481,184.000,0.085,0.078,0.116,0.129,1.705,0.007
2019-12-20,320.460,321.970,319.390,320.730,311.800,147142100,308.869,309.922,185.000,0.082,0.077,0.128,0.129,1.693,0.007
2019-12-23,321.590,321.650,321.060,321.220,312.276,52990000,309.368,310.366,186.000,0.075,0.077,0.121,0.129,1.683,0.007
2019-12-24,321.470,321.520,320.900,321.230,312.286,20270000,309.873,310.792,187.000,0.076,0.074,0.125,0.129,1.695,0.007
2019-12-26,321.650,322.950,321.640,322.940,313.949,30911200,310.354,311.268,188.000,0.088,0.075,0.142,0.129,1.727,0.008
2019-12-27,323.740,323.800,322.280,322.860,313.871,42528800,310.844,311.723,189.000,0.086,0.074,0.134,0.129,1.719,0.007
2019-12-30,322.950,323.100,320.550,321.080,312.140,49729100,311.280,312.090,190.000,0.075,0.076,0.144,0.129,1.683,0.007
2019-12-31,320.530,322.130,320.150,321.860,312.899,57077300,311.757,312.473,191.000,0.075,0.067,0.176,0.129,1.732,0.007